version: "3.8"
services:
  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: db-mongo
    ports:
      - "27017:27017"
    command: --nojournal

  orion-ld:
    image: fiware/orion-ld:latest
    hostname: orion-ld
    container_name: fiware-orion-ld
    depends_on:
      - mongo-db
    ports:
      - "1026:1026"
    command: -dbhost mongo-db -logLevel DEBUG